language: scala
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
before_install:
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
- sudo add-apt-repository "deb http://cran.csiro.au/bin/linux/ubuntu precise/"
- sudo apt-get update -qq
- sudo apt-get install -y r-base
install:
- git clone https://omnia-bamboo:$OMNIA_CI_PASSWORD@github.com/CommBank/ci.git
- ci/sbt-setup.sh
- wget http://rforge.net/Rserve/snapshot/Rserve_1.8-0.tar.gz
- sudo R CMD INSTALL Rserve_1.8-0.tar.gz
- R CMD Rserve
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package'
- ci/sbt-deploy.sh
after_script:
- rm -rf ci
env:
  global:
  - secure: Bzzeu3juqhsLhN1BgCVj7LWvNjZtWzQ4M/5cyUS5M2xXllrOKSR6NilPA0syB1UgtnKegwhVchCqE8E+CmEiVvbzIylMnR7rTmgThJ7L0zn/EAbi+yN1k471DvYBLCvigtLWNzaEX1bIkXj90ezvq+UplMOBtDOSI1P5Fex2mjw=
  - secure: MrIu6A3V5/O51xgat3O+kkZ/knVpLQTQOZnrGF/6XSmIQ7e/CDUDZIEDXV7rONE+ql8BN3QjYko6zF+qvqiYHuTNag/FJbSR0pjnYYrfL33JZGBwkj2GYkxXtB0PsSeRRk6ABoEy8+JsQaK3QctpbaA3F9YZSZepKLpQYxshFiA=
